language: node_js
node_js:
  - '10.13.0'
script:
  - omg validate
  - omg build -t test
  - omg run exec -a x=1 -a y=2 -a z=2 -e one=one --image test
before_script:
  - npm i omg
services:
  - docker
