version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: omg-install
          command: npm i omg
      - run:
          name: omg-validate
          command: npx omg validate
      - run:
          name: omg-build
          command: npx omg build -t test
      - run:
          name: omg-exec-exec
          command: npx omg exec exec -a x=1 -a y=2 -a z=2 -e one=one -i test
